declare deprecation of enterprise search plugin
logstash-plugins/logstash-integration-elastic_enterprise_search pull request #22
Opened 2024-12-19 14:35 UTC by kaisecheng

The Enterprise Search product is deprecated and will not be included in the Elastic Stack 9.x release.
As a result, the App Search and Workplace Search plugins are also deprecated. These plugins will only receive security updates and critical bug fixes moving forward.

This commit added deprecation log

fixes: https://github.com/logstash-plugins/logstash-integration-elastic_enterprise_search/issues/20, https://github.com/logstash-plugins/logstash-integration-elastic_enterprise_search/issues/21

2024-12-19 17:37 UTC, kaisecheng commented on lib/logstash/outputs/elastic_app_search.rb
> +      "For more details, please visit https://www.elastic.co/guide/en/enterprise-search/current/app-search-workplace-search.html"
@flexitrev same question here about the link https://www.elastic.co/guide/en/enterprise-search/current/app-search-workplace-search.html 
The instruction is a bit vague to me

2024-12-19 22:19 UTC, donoghuc approved these changes
LGTM. I think the 3.x series of this plugin will be going in to 9.x for LS and 2.x -> 8.x. Do we need the deprecation log in the 2 series as well? Or does this only apply to removal in the 9.x?

2024-12-19 22:52 UTC, kaisecheng commented
@donoghuc Thanks for the reviews. We maintain a single series of plugin. 3.0.0 is included in 8.17. 
Although the default distribution of v9 will not include this plugin, user can manually install it. Whenever, the plugin is used, the deprecation log should print and give instructions to the next steps.

2024-12-19 23:00 UTC, donoghuc commented
Ah, sorry I confused this with some of the other plugins i've been working on. Thanks that makes sense! 🙃 ERRTOOMANYPLUGINS

2025-01-02 18:38 UTC, flexitrev requested changes
I made some changes to the deprecation message that I think are a bit clearer.

2025-01-02 18:38 UTC, flexitrev commented on lib/logstash/outputs/elastic_app_search.rb
> +    log_message = "The App Search product is deprecated and excluded from the version 9 of the Elastic Stack. " +
```suggestion
    log_message = "The App Search product is deprecated and not supported from version 9 of the Elastic Stack. " +
```

2025-01-02 18:38 UTC, flexitrev commented on lib/logstash/outputs/elastic_app_search.rb
> +      "We recommend transitioning to our native Elasticsearch tools. " +
```suggestion
      "Please migrate to the Elasticsearch Connector for continued support." +
```

2025-01-02 18:38 UTC, flexitrev commented on lib/logstash/outputs/elastic_app_search.rb
> +      "For more details, please visit https://www.elastic.co/guide/en/enterprise-search/current/app-search-workplace-search.html"
```suggestion
      "For more details, please visit https://www.elastic.co/guide/en/search-ui/current/tutorials-elasticsearch.html"
```

2025-01-02 18:38 UTC, flexitrev commented on lib/logstash/outputs/elastic_app_search.rb
> +      "For more details, please visit https://www.elastic.co/guide/en/enterprise-search/current/app-search-workplace-search.html"
I changed the link to the Elasticsearch connector. I think it's better to direct customers to the software they should use rather than another deprecation message.

2025-01-03 14:04 UTC, jsvd commented on lib/logstash/outputs/elastic_app_search.rb
> +      "We recommend transitioning to our native Elasticsearch tools. " +
I believe you mean Elastic Connectors https://www.elastic.co/guide/en/elasticsearch/reference/master/es-connectors.html

2025-01-03 17:51 UTC, flexitrev approved these changes
LGTM

2025-01-03 20:57 UTC, merged